# -----------------------------------------------------------------------------
# Imports
# -----------------------------------------------------------------------------
import re
from bs4 import BeautifulSoup
from jsonom.get_data import PronomData

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------


class TestPronomData:
    def test_init(self):
        pronom_data = PronomData("test")
        assert pronom_data.base_url == "https://www.nationalarchives.gov.uk"
        assert pronom_data.url == "test"
        pronom_data = PronomData("/test")
        assert pronom_data.url == "test"


class TestPronomDataMethods:
    pronom = PronomData("aboutapps/pronom/droid-signature-files.htm")

    def test_text(self):
        assert (
            "This page contains an archive of all previously released "
            "signature files. Signature files are generated by PRONOM "
            "and used by DROID for file format identification. The "
            "signatures are presented here in xml form, each xml file "
            "contains multiple signatures that were released at the same time."
            in self.pronom.text()
        )
        assert re.search(
            r'Version="12" DateCreated="2006-08-23T14:52:24"',
            self.pronom.text("documents/DROID_SignatureFile_V12.xml"),
        )

    def test_soup(self):
        assert isinstance(self.pronom.soup(), BeautifulSoup)
        assert (
            self.pronom.soup().title.get_text().strip()
            == "The National Archives | PRONOM | DROID signatures"
        )
